# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
      adapter: mysql
      encoding: utf8
      reconnect: false
      database: lotto_development
      pool: 5
      username: root
      password: depassion
  
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

