development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: lotto_development
  pool: 5
  username: root
  password: depassion
  
test:  
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: lotto_test  
  pool: 5
  username: root
  password: depassion
